python .\scripts\card_renderer.py .\cards\000-void.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\001-justice.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\002-strength.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\003-death.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\004-the_wall.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\005-temperance.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\006-branch.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\007-thm.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\008-the_high_priestess.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\009-the_moon.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\010-the_emperator.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\011-the_hierophant.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\012-the_tower.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\013-the_merge.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\014-hope.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\015-the_temple.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\016-the_sumit.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\017-diamond.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\018-the_hermit.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\019-intuition.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\020-the_stone.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\021-mountains.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\022-the_shadow.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\023-opposite.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\024-the_oak.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\025-ripples.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\026-the_emperatris.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\027-bundle.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\028-the_devil.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\029-the_sun.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\030-the_star.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\031-Jugment.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\032-the_fortune.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\033-vision.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\034-the_lovers.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\035-magician.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\036-the_link.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\037-holding_together.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\038-the_chariot.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\039-the_loop.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\040-standstill.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\041-trinity.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\042-gather.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\043-the_clan.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\044-the_core.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\045-inner_truth.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\046-the_world.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\047-the_fool.frag .\assets\tarot-merge-normalized.png
python .\scripts\card_renderer.py .\cards\048-enlightenment.frag .\assets\tarot-merge-normalized.png
